export type ExerciseLevel = "Iniciante" | "Intermediário" | "Avançado";
export type ExerciseLocation = "Academia" | "Em casa";
export type Impact = "baixo" | "moderado" | "alto";

export type Exercise = {
  id: string;
  name: string;
  muscleGroups: string[];
  equipment: string;
  locations: ExerciseLocation[];
  movement: "warmup" | "squat" | "hinge" | "glute" | "horizontal_push" | "vertical_push" | "horizontal_pull" | "vertical_pull" | "arms" | "core" | "cardio" | "mobility" | "cooldown";
  level: ExerciseLevel;
  impact: Impact;
  tags: string[];
  avoidWhen: string[];
  instructions: string;
  commonErrors: string;
  alternativeIds: string[];
};

export const EXERCISE_DATABASE_VERSION = "2.0";

export const exercises: Exercise[] = [
  { id: "walk", name: "Caminhada leve", muscleGroups: ["Corpo inteiro"], equipment: "Esteira ou espaço livre", locations: ["Academia", "Em casa"], movement: "warmup", level: "Iniciante", impact: "baixo", tags: ["aquecimento", "baixo-impacto", "cardio"], avoidWhen: [], instructions: "Caminhe em ritmo confortável, respirando sem prender o ar.", commonErrors: "Começar rápido demais ou inclinar o tronco.", alternativeIds: ["bike", "march"] },
  { id: "bike", name: "Bicicleta ergométrica leve", muscleGroups: ["Pernas"], equipment: "Bicicleta ergométrica", locations: ["Academia"], movement: "warmup", level: "Iniciante", impact: "baixo", tags: ["aquecimento", "baixo-impacto", "cardio"], avoidWhen: ["knee_acute"], instructions: "Ajuste o banco para não fechar demais o joelho e pedale leve.", commonErrors: "Banco baixo e resistência excessiva.", alternativeIds: ["walk", "march"] },
  { id: "march", name: "Marcha estacionária", muscleGroups: ["Corpo inteiro"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "warmup", level: "Iniciante", impact: "baixo", tags: ["aquecimento", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Alterne os pés sem impacto, mantendo postura alta.", commonErrors: "Bater os pés ou acelerar além do confortável.", alternativeIds: ["walk"] },
  { id: "cat_cow", name: "Mobilidade gato-vaca", muscleGroups: ["Coluna", "Core"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "mobility", level: "Iniciante", impact: "baixo", tags: ["mobilidade", "baixo-impacto"], avoidWhen: ["wrist_acute"], instructions: "Movimente a coluna devagar, acompanhando a respiração.", commonErrors: "Forçar amplitude ou mover rápido.", alternativeIds: ["pelvic_tilt"] },
  { id: "pelvic_tilt", name: "Inclinação pélvica com respiração", muscleGroups: ["Core", "Assoalho pélvico"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["respiracao", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Expire suavemente, aproxime as costelas e faça uma pequena inclinação pélvica sem prender o ar.", commonErrors: "Contrair com força máxima ou empurrar o abdômen para fora.", alternativeIds: ["heel_slide"] },
  { id: "heel_slide", name: "Deslizamento de calcanhar", muscleGroups: ["Core", "Quadril"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["core", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Expire e deslize um calcanhar sem perder o controle do tronco.", commonErrors: "Arquear a lombar ou prender a respiração.", alternativeIds: ["pelvic_tilt", "bird_dog"] },
  { id: "bird_dog", name: "Bird dog", muscleGroups: ["Core", "Glúteos", "Lombar"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["core", "estabilidade", "baixo-impacto"], avoidWhen: ["wrist_acute"], instructions: "Alongue braço e perna opostos mantendo quadris nivelados.", commonErrors: "Girar o quadril ou arquear a lombar.", alternativeIds: ["heel_slide", "dead_bug"] },
  { id: "dead_bug", name: "Dead bug", muscleGroups: ["Core"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Intermediário", impact: "baixo", tags: ["core", "estabilidade"], avoidWhen: ["postpartum", "abdominal_symptoms"], instructions: "Mova membros opostos sem perder a posição das costelas.", commonErrors: "Arquear a lombar ou fazer rápido.", alternativeIds: ["heel_slide", "bird_dog"] },
  { id: "plank_incline", name: "Prancha inclinada", muscleGroups: ["Core", "Ombros"], equipment: "Banco ou parede", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["core", "isometria"], avoidWhen: ["shoulder_acute", "hypertension", "postpartum"], instructions: "Mantenha o corpo alinhado e respire continuamente.", commonErrors: "Prender o ar ou deixar o quadril cair.", alternativeIds: ["bird_dog", "pelvic_tilt"] },
  { id: "box_squat", name: "Agachamento no banco", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Banco", locations: ["Em casa", "Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["pernas", "baixo-impacto"], avoidWhen: ["knee_acute"], instructions: "Sente o quadril no banco com controle e levante empurrando o chão.", commonErrors: "Joelhos colapsarem para dentro ou cair no banco.", alternativeIds: ["leg_press", "glute_bridge"] },
  { id: "goblet_squat", name: "Agachamento goblet", muscleGroups: ["Quadríceps", "Glúteos", "Core"], equipment: "Halter", locations: ["Em casa", "Academia"], movement: "squat", level: "Intermediário", impact: "baixo", tags: ["pernas", "forca"], avoidWhen: ["knee_acute", "back_acute", "postpartum"], instructions: "Segure o halter junto ao peito e agache dentro de uma amplitude confortável.", commonErrors: "Perder a postura ou forçar profundidade.", alternativeIds: ["box_squat", "leg_press"] },
  { id: "leg_press", name: "Leg press", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Leg press", locations: ["Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["pernas", "maquina"], avoidWhen: ["knee_acute", "back_acute"], instructions: "Desça até manter quadril e lombar apoiados; empurre sem travar os joelhos.", commonErrors: "Descer além do controle ou tirar o quadril do encosto.", alternativeIds: ["box_squat", "goblet_squat"] },
  { id: "split_squat_support", name: "Agachamento dividido com apoio", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Apoio estável", locations: ["Em casa", "Academia"], movement: "squat", level: "Intermediário", impact: "baixo", tags: ["unilateral", "pernas"], avoidWhen: ["knee_acute", "balance_issue"], instructions: "Use apoio, desça verticalmente e mantenha o joelho alinhado.", commonErrors: "Perder equilíbrio ou rodar o joelho.", alternativeIds: ["box_squat", "leg_press"] },
  { id: "hip_hinge_wall", name: "Dobradiça de quadril na parede", muscleGroups: ["Posteriores", "Glúteos"], equipment: "Parede", locations: ["Em casa", "Academia"], movement: "hinge", level: "Iniciante", impact: "baixo", tags: ["tecnica", "posterior"], avoidWhen: ["back_acute"], instructions: "Leve o quadril para trás até tocar a parede, mantendo a coluna neutra.", commonErrors: "Agachar em vez de dobrar o quadril.", alternativeIds: ["glute_bridge"] },
  { id: "romanian_deadlift_db", name: "Levantamento romeno com halteres", muscleGroups: ["Posteriores", "Glúteos", "Lombar"], equipment: "Halteres", locations: ["Em casa", "Academia"], movement: "hinge", level: "Intermediário", impact: "baixo", tags: ["posterior", "forca"], avoidWhen: ["back_acute", "postpartum"], instructions: "Desça os halteres junto às pernas levando o quadril para trás.", commonErrors: "Arredondar a coluna ou afastar a carga do corpo.", alternativeIds: ["hip_hinge_wall", "leg_curl"] },
  { id: "leg_curl", name: "Mesa flexora", muscleGroups: ["Posteriores"], equipment: "Mesa flexora", locations: ["Academia"], movement: "hinge", level: "Iniciante", impact: "baixo", tags: ["posterior", "maquina"], avoidWhen: ["knee_acute"], instructions: "Flexione os joelhos sem levantar o quadril do apoio.", commonErrors: "Usar impulso ou encurtar a amplitude.", alternativeIds: ["romanian_deadlift_db", "glute_bridge"] },
  { id: "glute_bridge", name: "Ponte de glúteos", muscleGroups: ["Glúteos", "Posteriores"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "glute", level: "Iniciante", impact: "baixo", tags: ["gluteos", "baixo-impacto", "pos-parto"], avoidWhen: ["abdominal_symptoms"], instructions: "Expire, pressione os pés e eleve o quadril sem arquear a lombar.", commonErrors: "Subir pelas costas ou prender o ar.", alternativeIds: ["hip_thrust_machine", "hip_hinge_wall"] },
  { id: "hip_thrust_machine", name: "Hip thrust na máquina", muscleGroups: ["Glúteos", "Posteriores"], equipment: "Máquina de hip thrust", locations: ["Academia"], movement: "glute", level: "Intermediário", impact: "baixo", tags: ["gluteos", "maquina"], avoidWhen: ["postpartum", "abdominal_symptoms"], instructions: "Apoie as escápulas, eleve o quadril e finalize com costelas alinhadas.", commonErrors: "Hiperestender a lombar ou usar carga sem controle.", alternativeIds: ["glute_bridge"] },
  { id: "wall_pushup", name: "Flexão na parede", muscleGroups: ["Peito", "Tríceps", "Ombros"], equipment: "Parede", locations: ["Em casa", "Academia"], movement: "horizontal_push", level: "Iniciante", impact: "baixo", tags: ["superiores", "baixo-impacto", "pos-parto"], avoidWhen: ["shoulder_acute", "wrist_acute"], instructions: "Aproxime o peito da parede com cotovelos levemente diagonais.", commonErrors: "Abrir demais os cotovelos ou perder o alinhamento.", alternativeIds: ["chest_press"] },
  { id: "chest_press", name: "Supino máquina", muscleGroups: ["Peito", "Tríceps", "Ombros"], equipment: "Máquina de supino", locations: ["Academia"], movement: "horizontal_push", level: "Iniciante", impact: "baixo", tags: ["superiores", "maquina"], avoidWhen: ["shoulder_acute"], instructions: "Ajuste o banco, mantenha escápulas apoiadas e empurre sem travar os cotovelos.", commonErrors: "Ombros subirem ou amplitude dolorosa.", alternativeIds: ["wall_pushup", "db_floor_press"] },
  { id: "db_floor_press", name: "Supino com halteres no chão", muscleGroups: ["Peito", "Tríceps"], equipment: "Halteres e colchonete", locations: ["Em casa", "Academia"], movement: "horizontal_push", level: "Intermediário", impact: "baixo", tags: ["superiores"], avoidWhen: ["shoulder_acute", "postpartum"], instructions: "Desça até os braços tocarem suavemente o chão e empurre com controle.", commonErrors: "Bater os braços no chão ou prender o ar.", alternativeIds: ["wall_pushup", "chest_press"] },
  { id: "landmine_press", name: "Desenvolvimento landmine", muscleGroups: ["Ombros", "Tríceps"], equipment: "Landmine", locations: ["Academia"], movement: "vertical_push", level: "Intermediário", impact: "baixo", tags: ["ombros", "pegada-neutra"], avoidWhen: ["shoulder_acute", "postpartum"], instructions: "Empurre a barra em diagonal sem elevar o ombro.", commonErrors: "Arquear a lombar ou encolher o ombro.", alternativeIds: ["wall_pushup", "chest_press"] },
  { id: "seated_row", name: "Remada sentada", muscleGroups: ["Costas", "Bíceps"], equipment: "Máquina ou cabo", locations: ["Academia"], movement: "horizontal_pull", level: "Iniciante", impact: "baixo", tags: ["costas", "maquina"], avoidWhen: ["back_acute"], instructions: "Puxe os cotovelos para trás mantendo peito apoiado ou tronco estável.", commonErrors: "Usar balanço ou elevar os ombros.", alternativeIds: ["band_row", "chest_supported_row"] },
  { id: "band_row", name: "Remada com elástico", muscleGroups: ["Costas", "Bíceps"], equipment: "Elástico", locations: ["Em casa", "Academia"], movement: "horizontal_pull", level: "Iniciante", impact: "baixo", tags: ["costas", "baixo-impacto", "pos-parto"], avoidWhen: ["shoulder_acute"], instructions: "Puxe o elástico em direção às costelas e retorne devagar.", commonErrors: "Inclinar o tronco ou encolher os ombros.", alternativeIds: ["seated_row"] },
  { id: "chest_supported_row", name: "Remada com peito apoiado", muscleGroups: ["Costas", "Bíceps"], equipment: "Banco inclinado e halteres", locations: ["Academia"], movement: "horizontal_pull", level: "Intermediário", impact: "baixo", tags: ["costas", "estabilidade"], avoidWhen: ["abdominal_symptoms"], instructions: "Mantenha o peito apoiado e puxe os halteres em direção ao quadril.", commonErrors: "Encolher os ombros ou tirar o peito do banco.", alternativeIds: ["seated_row", "band_row"] },
  { id: "lat_pulldown", name: "Puxada frontal", muscleGroups: ["Costas", "Bíceps"], equipment: "Puxador", locations: ["Academia"], movement: "vertical_pull", level: "Iniciante", impact: "baixo", tags: ["costas", "maquina"], avoidWhen: ["shoulder_acute"], instructions: "Puxe a barra à frente até a parte alta do peito, sem balançar.", commonErrors: "Puxar atrás da cabeça ou inclinar demais o tronco.", alternativeIds: ["band_row", "seated_row"] },
  { id: "biceps_curl", name: "Rosca com halteres", muscleGroups: ["Bíceps"], equipment: "Halteres", locations: ["Em casa", "Academia"], movement: "arms", level: "Iniciante", impact: "baixo", tags: ["bracos"], avoidWhen: [], instructions: "Flexione os cotovelos sem mover os ombros e desça devagar.", commonErrors: "Balançar o corpo ou avançar os cotovelos.", alternativeIds: ["band_row"] },
  { id: "triceps_cable", name: "Tríceps na polia", muscleGroups: ["Tríceps"], equipment: "Polia", locations: ["Academia"], movement: "arms", level: "Iniciante", impact: "baixo", tags: ["bracos"], avoidWhen: ["elbow_acute"], instructions: "Estenda os cotovelos mantendo braços junto ao corpo.", commonErrors: "Mover os ombros ou usar balanço.", alternativeIds: ["wall_pushup"] },
  { id: "calf_raise", name: "Elevação de panturrilhas", muscleGroups: ["Panturrilhas"], equipment: "Apoio estável", locations: ["Em casa", "Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["pernas", "equilibrio"], avoidWhen: ["ankle_acute", "balance_issue"], instructions: "Suba e desça os calcanhares com apoio e controle.", commonErrors: "Usar impulso ou deixar os tornozelos cederem.", alternativeIds: ["walk"] },
  { id: "step_touch", name: "Passo lateral sem salto", muscleGroups: ["Pernas", "Cardiorrespiratório"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "cardio", level: "Iniciante", impact: "baixo", tags: ["cardio", "baixo-impacto", "pos-parto"], avoidWhen: ["knee_acute", "balance_issue"], instructions: "Dê passos laterais curtos sem saltar e mantenha ritmo confortável.", commonErrors: "Cruzar os pés ou aumentar impacto.", alternativeIds: ["walk", "march"] },
  { id: "incline_walk", name: "Caminhada inclinada", muscleGroups: ["Pernas", "Cardiorrespiratório"], equipment: "Esteira", locations: ["Academia"], movement: "cardio", level: "Intermediário", impact: "baixo", tags: ["cardio", "condicionamento"], avoidWhen: ["knee_acute", "cardiovascular"], instructions: "Use inclinação moderada mantendo conversa curta possível.", commonErrors: "Apoiar peso nos braços ou exagerar inclinação.", alternativeIds: ["walk", "bike"] },
  { id: "hip_flexor_stretch", name: "Alongamento de flexores do quadril", muscleGroups: ["Quadril"], equipment: "Colchonete ou banco", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["alongamento", "mobilidade"], avoidWhen: ["knee_acute"], instructions: "Mantenha o tronco alto e avance suavemente o quadril.", commonErrors: "Arquear a lombar ou forçar o joelho.", alternativeIds: ["breathing_reset"] },
  { id: "chest_stretch", name: "Alongamento peitoral na parede", muscleGroups: ["Peito", "Ombros"], equipment: "Parede", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["alongamento", "mobilidade"], avoidWhen: ["shoulder_acute"], instructions: "Apoie a mão e gire o tronco apenas até sentir tensão leve.", commonErrors: "Forçar a articulação ou elevar o ombro.", alternativeIds: ["breathing_reset"] },
  { id: "breathing_reset", name: "Respiração de recuperação", muscleGroups: ["Respiratório", "Core"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["respiracao", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Inspire pelo nariz e expire lentamente sem fazer força.", commonErrors: "Prender o ar ou tentar maximizar a inspiração.", alternativeIds: [] },
];

export const exerciseById = new Map(exercises.map((exercise) => [exercise.id, exercise]));
