export type ExerciseLevel = "Iniciante" | "Intermediário" | "Avançado";
export type ExerciseLocation = "Academia" | "Em casa";
export type Impact = "baixo" | "moderado" | "alto";

export type Exercise = {
  id: string;
  name: string;
  muscleGroups: string[];
  equipment: string;
  locations: ExerciseLocation[];
  movement: "warmup" | "squat" | "hinge" | "glute" | "horizontal_push" | "vertical_push" | "horizontal_pull" | "vertical_pull" | "arms" | "core" | "cardio" | "mobility" | "cooldown";
  level: ExerciseLevel;
  impact: Impact;
  tags: string[];
  avoidWhen: string[];
  instructions: string;
  commonErrors: string;
  alternativeIds: string[];
};

export const EXERCISE_DATABASE_VERSION = "4.1";

export const exercises: Exercise[] = [
  { id: "walk", name: "Caminhada leve", muscleGroups: ["Corpo inteiro"], equipment: "Esteira ou espaço livre", locations: ["Academia", "Em casa"], movement: "warmup", level: "Iniciante", impact: "baixo", tags: ["aquecimento", "baixo-impacto", "cardio"], avoidWhen: [], instructions: "Caminhe em ritmo confortável, respirando sem prender o ar.", commonErrors: "Começar rápido demais ou inclinar o tronco.", alternativeIds: ["bike", "march"] },
  { id: "bike", name: "Bicicleta ergométrica leve", muscleGroups: ["Pernas"], equipment: "Bicicleta ergométrica", locations: ["Academia"], movement: "warmup", level: "Iniciante", impact: "baixo", tags: ["aquecimento", "baixo-impacto", "cardio"], avoidWhen: ["knee_acute"], instructions: "Ajuste o banco para não fechar demais o joelho e pedale leve.", commonErrors: "Banco baixo e resistência excessiva.", alternativeIds: ["walk", "march"] },
  { id: "march", name: "Marcha estacionária", muscleGroups: ["Corpo inteiro"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "warmup", level: "Iniciante", impact: "baixo", tags: ["aquecimento", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Alterne os pés sem impacto, mantendo postura alta.", commonErrors: "Bater os pés ou acelerar além do confortável.", alternativeIds: ["walk"] },
  { id: "cat_cow", name: "Mobilidade gato-vaca", muscleGroups: ["Coluna", "Core"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "mobility", level: "Iniciante", impact: "baixo", tags: ["mobilidade", "baixo-impacto"], avoidWhen: ["wrist_acute"], instructions: "Movimente a coluna devagar, acompanhando a respiração.", commonErrors: "Forçar amplitude ou mover rápido.", alternativeIds: ["pelvic_tilt"] },
  { id: "pelvic_tilt", name: "Inclinação pélvica com respiração", muscleGroups: ["Core", "Assoalho pélvico"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["respiracao", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Expire suavemente, aproxime as costelas e faça uma pequena inclinação pélvica sem prender o ar.", commonErrors: "Contrair com força máxima ou empurrar o abdômen para fora.", alternativeIds: ["heel_slide"] },
  { id: "heel_slide", name: "Deslizamento de calcanhar", muscleGroups: ["Core", "Quadril"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["core", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Expire e deslize um calcanhar sem perder o controle do tronco.", commonErrors: "Arquear a lombar ou prender a respiração.", alternativeIds: ["pelvic_tilt", "bird_dog"] },
  { id: "bird_dog", name: "Bird dog", muscleGroups: ["Core", "Glúteos", "Lombar"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["core", "estabilidade", "baixo-impacto"], avoidWhen: ["wrist_acute"], instructions: "Alongue braço e perna opostos mantendo quadris nivelados.", commonErrors: "Girar o quadril ou arquear a lombar.", alternativeIds: ["heel_slide", "dead_bug"] },
  { id: "dead_bug", name: "Dead bug", muscleGroups: ["Core"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Intermediário", impact: "baixo", tags: ["core", "estabilidade"], avoidWhen: ["postpartum", "abdominal_symptoms"], instructions: "Mova membros opostos sem perder a posição das costelas.", commonErrors: "Arquear a lombar ou fazer rápido.", alternativeIds: ["heel_slide", "bird_dog"] },
  { id: "plank_incline", name: "Prancha inclinada", muscleGroups: ["Core", "Ombros"], equipment: "Banco ou parede", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["core", "isometria"], avoidWhen: ["shoulder_acute", "hypertension", "postpartum"], instructions: "Mantenha o corpo alinhado e respire continuamente.", commonErrors: "Prender o ar ou deixar o quadril cair.", alternativeIds: ["bird_dog", "pelvic_tilt"] },
  { id: "box_squat", name: "Agachamento no banco", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Banco", locations: ["Em casa", "Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["pernas", "baixo-impacto"], avoidWhen: ["knee_acute"], instructions: "Sente o quadril no banco com controle e levante empurrando o chão.", commonErrors: "Joelhos colapsarem para dentro ou cair no banco.", alternativeIds: ["leg_press", "glute_bridge"] },
  { id: "goblet_squat", name: "Agachamento goblet", muscleGroups: ["Quadríceps", "Glúteos", "Core"], equipment: "Halter", locations: ["Em casa", "Academia"], movement: "squat", level: "Intermediário", impact: "baixo", tags: ["pernas", "forca"], avoidWhen: ["knee_acute", "back_acute", "postpartum"], instructions: "Segure o halter junto ao peito e agache dentro de uma amplitude confortável.", commonErrors: "Perder a postura ou forçar profundidade.", alternativeIds: ["box_squat", "leg_press"] },
  { id: "leg_press", name: "Leg press", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Leg press", locations: ["Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["pernas", "maquina"], avoidWhen: ["knee_acute", "back_acute"], instructions: "Desça até manter quadril e lombar apoiados; empurre sem travar os joelhos.", commonErrors: "Descer além do controle ou tirar o quadril do encosto.", alternativeIds: ["box_squat", "goblet_squat"] },
  { id: "split_squat_support", name: "Agachamento dividido com apoio", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Apoio estável", locations: ["Em casa", "Academia"], movement: "squat", level: "Intermediário", impact: "baixo", tags: ["unilateral", "pernas"], avoidWhen: ["knee_acute", "balance_issue"], instructions: "Use apoio, desça verticalmente e mantenha o joelho alinhado.", commonErrors: "Perder equilíbrio ou rodar o joelho.", alternativeIds: ["box_squat", "leg_press"] },
  { id: "hip_hinge_wall", name: "Dobradiça de quadril na parede", muscleGroups: ["Posteriores", "Glúteos"], equipment: "Parede", locations: ["Em casa", "Academia"], movement: "hinge", level: "Iniciante", impact: "baixo", tags: ["tecnica", "posterior"], avoidWhen: ["back_acute"], instructions: "Leve o quadril para trás até tocar a parede, mantendo a coluna neutra.", commonErrors: "Agachar em vez de dobrar o quadril.", alternativeIds: ["glute_bridge"] },
  { id: "romanian_deadlift_db", name: "Levantamento romeno com halteres", muscleGroups: ["Posteriores", "Glúteos", "Lombar"], equipment: "Halteres", locations: ["Em casa", "Academia"], movement: "hinge", level: "Intermediário", impact: "baixo", tags: ["posterior", "forca"], avoidWhen: ["back_acute", "postpartum"], instructions: "Desça os halteres junto às pernas levando o quadril para trás.", commonErrors: "Arredondar a coluna ou afastar a carga do corpo.", alternativeIds: ["hip_hinge_wall", "leg_curl"] },
  { id: "leg_curl", name: "Mesa flexora", muscleGroups: ["Posteriores"], equipment: "Mesa flexora", locations: ["Academia"], movement: "hinge", level: "Iniciante", impact: "baixo", tags: ["posterior", "maquina"], avoidWhen: ["knee_acute"], instructions: "Flexione os joelhos sem levantar o quadril do apoio.", commonErrors: "Usar impulso ou encurtar a amplitude.", alternativeIds: ["romanian_deadlift_db", "glute_bridge"] },
  { id: "glute_bridge", name: "Ponte de glúteos", muscleGroups: ["Glúteos", "Posteriores"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "glute", level: "Iniciante", impact: "baixo", tags: ["gluteos", "baixo-impacto", "pos-parto"], avoidWhen: ["abdominal_symptoms"], instructions: "Expire, pressione os pés e eleve o quadril sem arquear a lombar.", commonErrors: "Subir pelas costas ou prender o ar.", alternativeIds: ["hip_thrust_machine", "hip_hinge_wall"] },
  { id: "hip_thrust_machine", name: "Hip thrust na máquina", muscleGroups: ["Glúteos", "Posteriores"], equipment: "Máquina de hip thrust", locations: ["Academia"], movement: "glute", level: "Intermediário", impact: "baixo", tags: ["gluteos", "maquina"], avoidWhen: ["postpartum", "abdominal_symptoms"], instructions: "Apoie as escápulas, eleve o quadril e finalize com costelas alinhadas.", commonErrors: "Hiperestender a lombar ou usar carga sem controle.", alternativeIds: ["glute_bridge"] },
  { id: "wall_pushup", name: "Flexão na parede", muscleGroups: ["Peito", "Tríceps", "Ombros"], equipment: "Parede", locations: ["Em casa", "Academia"], movement: "horizontal_push", level: "Iniciante", impact: "baixo", tags: ["superiores", "baixo-impacto", "pos-parto"], avoidWhen: ["shoulder_acute", "wrist_acute"], instructions: "Aproxime o peito da parede com cotovelos levemente diagonais.", commonErrors: "Abrir demais os cotovelos ou perder o alinhamento.", alternativeIds: ["chest_press"] },
  { id: "chest_press", name: "Supino máquina", muscleGroups: ["Peito", "Tríceps", "Ombros"], equipment: "Máquina de supino", locations: ["Academia"], movement: "horizontal_push", level: "Iniciante", impact: "baixo", tags: ["superiores", "maquina"], avoidWhen: ["shoulder_acute"], instructions: "Ajuste o banco, mantenha escápulas apoiadas e empurre sem travar os cotovelos.", commonErrors: "Ombros subirem ou amplitude dolorosa.", alternativeIds: ["wall_pushup", "db_floor_press"] },
  { id: "db_floor_press", name: "Supino com halteres no chão", muscleGroups: ["Peito", "Tríceps"], equipment: "Halteres e colchonete", locations: ["Em casa", "Academia"], movement: "horizontal_push", level: "Intermediário", impact: "baixo", tags: ["superiores"], avoidWhen: ["shoulder_acute", "postpartum"], instructions: "Desça até os braços tocarem suavemente o chão e empurre com controle.", commonErrors: "Bater os braços no chão ou prender o ar.", alternativeIds: ["wall_pushup", "chest_press"] },
  { id: "landmine_press", name: "Desenvolvimento landmine", muscleGroups: ["Ombros", "Tríceps"], equipment: "Landmine", locations: ["Academia"], movement: "vertical_push", level: "Intermediário", impact: "baixo", tags: ["ombros", "pegada-neutra"], avoidWhen: ["shoulder_acute", "postpartum"], instructions: "Empurre a barra em diagonal sem elevar o ombro.", commonErrors: "Arquear a lombar ou encolher o ombro.", alternativeIds: ["wall_pushup", "chest_press"] },
  { id: "seated_row", name: "Remada sentada", muscleGroups: ["Costas", "Bíceps"], equipment: "Máquina ou cabo", locations: ["Academia"], movement: "horizontal_pull", level: "Iniciante", impact: "baixo", tags: ["costas", "maquina"], avoidWhen: ["back_acute"], instructions: "Puxe os cotovelos para trás mantendo peito apoiado ou tronco estável.", commonErrors: "Usar balanço ou elevar os ombros.", alternativeIds: ["band_row", "chest_supported_row"] },
  { id: "band_row", name: "Remada com elástico", muscleGroups: ["Costas", "Bíceps"], equipment: "Elástico", locations: ["Em casa", "Academia"], movement: "horizontal_pull", level: "Iniciante", impact: "baixo", tags: ["costas", "baixo-impacto", "pos-parto"], avoidWhen: ["shoulder_acute"], instructions: "Puxe o elástico em direção às costelas e retorne devagar.", commonErrors: "Inclinar o tronco ou encolher os ombros.", alternativeIds: ["seated_row"] },
  { id: "chest_supported_row", name: "Remada com peito apoiado", muscleGroups: ["Costas", "Bíceps"], equipment: "Banco inclinado e halteres", locations: ["Academia"], movement: "horizontal_pull", level: "Intermediário", impact: "baixo", tags: ["costas", "estabilidade"], avoidWhen: ["abdominal_symptoms"], instructions: "Mantenha o peito apoiado e puxe os halteres em direção ao quadril.", commonErrors: "Encolher os ombros ou tirar o peito do banco.", alternativeIds: ["seated_row", "band_row"] },
  { id: "lat_pulldown", name: "Puxada frontal", muscleGroups: ["Costas", "Bíceps"], equipment: "Puxador", locations: ["Academia"], movement: "vertical_pull", level: "Iniciante", impact: "baixo", tags: ["costas", "maquina"], avoidWhen: ["shoulder_acute"], instructions: "Puxe a barra à frente até a parte alta do peito, sem balançar.", commonErrors: "Puxar atrás da cabeça ou inclinar demais o tronco.", alternativeIds: ["band_row", "seated_row"] },
  { id: "biceps_curl", name: "Rosca com halteres", muscleGroups: ["Bíceps"], equipment: "Halteres", locations: ["Em casa", "Academia"], movement: "arms", level: "Iniciante", impact: "baixo", tags: ["bracos"], avoidWhen: [], instructions: "Flexione os cotovelos sem mover os ombros e desça devagar.", commonErrors: "Balançar o corpo ou avançar os cotovelos.", alternativeIds: ["band_row"] },
  { id: "triceps_cable", name: "Tríceps na polia", muscleGroups: ["Tríceps"], equipment: "Polia", locations: ["Academia"], movement: "arms", level: "Iniciante", impact: "baixo", tags: ["bracos"], avoidWhen: ["elbow_acute"], instructions: "Estenda os cotovelos mantendo braços junto ao corpo.", commonErrors: "Mover os ombros ou usar balanço.", alternativeIds: ["wall_pushup"] },
  { id: "calf_raise", name: "Elevação de panturrilhas", muscleGroups: ["Panturrilhas"], equipment: "Apoio estável", locations: ["Em casa", "Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["pernas", "equilibrio"], avoidWhen: ["ankle_acute", "balance_issue"], instructions: "Suba e desça os calcanhares com apoio e controle.", commonErrors: "Usar impulso ou deixar os tornozelos cederem.", alternativeIds: ["walk"] },
  { id: "step_touch", name: "Passo lateral sem salto", muscleGroups: ["Pernas", "Cardiorrespiratório"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "cardio", level: "Iniciante", impact: "baixo", tags: ["cardio", "baixo-impacto", "pos-parto"], avoidWhen: ["knee_acute", "balance_issue"], instructions: "Dê passos laterais curtos sem saltar e mantenha ritmo confortável.", commonErrors: "Cruzar os pés ou aumentar impacto.", alternativeIds: ["walk", "march"] },
  { id: "incline_walk", name: "Caminhada inclinada", muscleGroups: ["Pernas", "Cardiorrespiratório"], equipment: "Esteira", locations: ["Academia"], movement: "cardio", level: "Intermediário", impact: "baixo", tags: ["cardio", "condicionamento"], avoidWhen: ["knee_acute", "cardiovascular"], instructions: "Use inclinação moderada mantendo conversa curta possível.", commonErrors: "Apoiar peso nos braços ou exagerar inclinação.", alternativeIds: ["walk", "bike"] },
  { id: "hip_flexor_stretch", name: "Alongamento de flexores do quadril", muscleGroups: ["Quadril"], equipment: "Colchonete ou banco", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["alongamento", "mobilidade"], avoidWhen: ["knee_acute"], instructions: "Mantenha o tronco alto e avance suavemente o quadril.", commonErrors: "Arquear a lombar ou forçar o joelho.", alternativeIds: ["breathing_reset"] },
  { id: "chest_stretch", name: "Alongamento peitoral na parede", muscleGroups: ["Peito", "Ombros"], equipment: "Parede", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["alongamento", "mobilidade"], avoidWhen: ["shoulder_acute"], instructions: "Apoie a mão e gire o tronco apenas até sentir tensão leve.", commonErrors: "Forçar a articulação ou elevar o ombro.", alternativeIds: ["breathing_reset"] },
  { id: "breathing_reset", name: "Respiração de recuperação", muscleGroups: ["Respiratório", "Core"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["respiracao", "baixo-impacto", "pos-parto"], avoidWhen: [], instructions: "Inspire pelo nariz e expire lentamente sem fazer força.", commonErrors: "Prender o ar ou tentar maximizar a inspiração.", alternativeIds: [] },
  { id: "elliptical", name: "Elíptico", muscleGroups: ["Pernas", "Cardiorrespiratório"], equipment: "Elíptico", locations: ["Academia"], movement: "cardio", level: "Iniciante", impact: "baixo", tags: ["cardio", "maquina", "baixo-impacto"], avoidWhen: ["balance_issue"], instructions: "Mantenha postura alta e uma cadência que permita controlar a respiração.", commonErrors: "Apoiar o peso nos braços ou acelerar sem controle.", alternativeIds: ["bike", "incline_walk"] },
  { id: "rowing_ergometer", name: "Remo ergômetro", muscleGroups: ["Costas", "Pernas", "Cardiorrespiratório"], equipment: "Remo ergômetro", locations: ["Academia"], movement: "cardio", level: "Intermediário", impact: "baixo", tags: ["cardio", "maquina", "corpo-inteiro"], avoidWhen: ["back_acute"], instructions: "Empurre com as pernas, estenda o quadril e finalize puxando o cabo até as costelas.", commonErrors: "Puxar primeiro com os braços ou arredondar a lombar.", alternativeIds: ["bike", "incline_walk"] },
  { id: "treadmill_intervals", name: "Intervalos na esteira", muscleGroups: ["Pernas", "Cardiorrespiratório"], equipment: "Esteira", locations: ["Academia"], movement: "cardio", level: "Intermediário", impact: "moderado", tags: ["cardio", "intervalado", "maquina"], avoidWhen: ["knee_acute", "balance_issue", "cardiovascular"], instructions: "Alterne blocos de ritmo confortável e acelerado sem perder a postura.", commonErrors: "Segurar nas barras ou aumentar velocidade e inclinação ao mesmo tempo.", alternativeIds: ["incline_walk", "elliptical"] },
  { id: "back_squat", name: "Agachamento com barra", muscleGroups: ["Quadríceps", "Glúteos", "Core"], equipment: "Barra e rack", locations: ["Academia"], movement: "squat", level: "Avançado", impact: "moderado", tags: ["peso-livre", "composto", "forca"], avoidWhen: ["knee_acute", "back_acute", "postpartum"], instructions: "Apoie a barra com estabilidade, agache com joelhos alinhados e suba mantendo o tronco firme.", commonErrors: "Perder a pressão abdominal, colapsar os joelhos ou usar amplitude sem controle.", alternativeIds: ["goblet_squat", "leg_press"] },
  { id: "hack_squat", name: "Hack squat", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Máquina hack", locations: ["Academia"], movement: "squat", level: "Intermediário", impact: "baixo", tags: ["maquina", "pernas", "forca"], avoidWhen: ["knee_acute", "back_acute"], instructions: "Mantenha quadril e costas apoiados e desça até a amplitude controlada.", commonErrors: "Descolar o quadril do encosto ou travar os joelhos.", alternativeIds: ["leg_press", "goblet_squat"] },
  { id: "smith_squat", name: "Agachamento no Smith", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Máquina Smith", locations: ["Academia"], movement: "squat", level: "Intermediário", impact: "baixo", tags: ["maquina", "pernas"], avoidWhen: ["knee_acute", "back_acute"], instructions: "Posicione os pés para manter o tronco confortável e controle toda a descida.", commonErrors: "Usar os pés perto demais da barra ou relaxar no fim da descida.", alternativeIds: ["leg_press", "box_squat"] },
  { id: "barbell_deadlift", name: "Levantamento terra com barra", muscleGroups: ["Posteriores", "Glúteos", "Costas"], equipment: "Barra e anilhas", locations: ["Academia"], movement: "hinge", level: "Avançado", impact: "moderado", tags: ["peso-livre", "composto", "forca"], avoidWhen: ["back_acute", "postpartum"], instructions: "Mantenha a barra próxima ao corpo e estenda joelhos e quadril em conjunto.", commonErrors: "Afastar a barra, arredondar a coluna ou hiperestender no topo.", alternativeIds: ["romanian_deadlift_db", "hip_hinge_wall"] },
  { id: "cable_pull_through", name: "Pull-through na polia", muscleGroups: ["Glúteos", "Posteriores"], equipment: "Polia baixa e corda", locations: ["Academia"], movement: "hinge", level: "Intermediário", impact: "baixo", tags: ["cabo", "posterior", "tecnica"], avoidWhen: ["back_acute"], instructions: "Leve o quadril para trás e estenda-o contraindo os glúteos, sem puxar com os braços.", commonErrors: "Transformar o movimento em agachamento ou arquear a lombar.", alternativeIds: ["romanian_deadlift_db", "hip_hinge_wall"] },
  { id: "barbell_hip_thrust", name: "Hip thrust com barra", muscleGroups: ["Glúteos", "Posteriores"], equipment: "Barra, anilhas e banco", locations: ["Academia"], movement: "glute", level: "Intermediário", impact: "baixo", tags: ["peso-livre", "gluteos", "forca"], avoidWhen: ["postpartum", "abdominal_symptoms"], instructions: "Apoie as escápulas no banco e eleve o quadril até alinhar joelhos, quadril e ombros.", commonErrors: "Hiperestender a lombar ou afastar os pés demais.", alternativeIds: ["hip_thrust_machine", "glute_bridge"] },
  { id: "cable_kickback", name: "Coice na polia", muscleGroups: ["Glúteos"], equipment: "Polia baixa e tornozeleira", locations: ["Academia"], movement: "glute", level: "Iniciante", impact: "baixo", tags: ["cabo", "gluteos", "isolador"], avoidWhen: ["balance_issue"], instructions: "Estenda o quadril mantendo a pelve estável e o tronco apoiado.", commonErrors: "Girar o quadril ou impulsionar a lombar.", alternativeIds: ["glute_bridge", "hip_thrust_machine"] },
  { id: "barbell_bench_press", name: "Supino reto com barra", muscleGroups: ["Peito", "Tríceps", "Ombros"], equipment: "Barra, anilhas e banco", locations: ["Academia"], movement: "horizontal_push", level: "Intermediário", impact: "baixo", tags: ["peso-livre", "composto", "forca"], avoidWhen: ["shoulder_acute"], instructions: "Mantenha os pés firmes e desça a barra com controle até uma amplitude confortável.", commonErrors: "Abrir demais os cotovelos ou tirar os ombros do banco.", alternativeIds: ["chest_press", "db_floor_press"] },
  { id: "incline_db_press", name: "Supino inclinado com halteres", muscleGroups: ["Peito", "Ombros", "Tríceps"], equipment: "Halteres e banco inclinado", locations: ["Academia"], movement: "horizontal_push", level: "Intermediário", impact: "baixo", tags: ["peso-livre", "superiores"], avoidWhen: ["shoulder_acute"], instructions: "Pressione os halteres acima do peito mantendo antebraços verticais.", commonErrors: "Banco muito inclinado ou halteres descendo fora do controle.", alternativeIds: ["chest_press", "db_floor_press"] },
  { id: "cable_fly", name: "Crucifixo na polia", muscleGroups: ["Peito", "Ombros"], equipment: "Polia dupla", locations: ["Academia"], movement: "horizontal_push", level: "Intermediário", impact: "baixo", tags: ["cabo", "isolador", "peito"], avoidWhen: ["shoulder_acute"], instructions: "Aproxime as mãos à frente do peito com cotovelos levemente flexionados.", commonErrors: "Alongar além do conforto ou transformar em empurrada.", alternativeIds: ["chest_press", "wall_pushup"] },
  { id: "shoulder_press_machine", name: "Desenvolvimento na máquina", muscleGroups: ["Ombros", "Tríceps"], equipment: "Máquina de desenvolvimento", locations: ["Academia"], movement: "vertical_push", level: "Iniciante", impact: "baixo", tags: ["maquina", "ombros"], avoidWhen: ["shoulder_acute", "hypertension"], instructions: "Ajuste o banco e empurre sem elevar os ombros ou prender a respiração.", commonErrors: "Pegada muito aberta ou arquear a lombar.", alternativeIds: ["landmine_press", "chest_press"] },
  { id: "dumbbell_shoulder_press", name: "Desenvolvimento com halteres", muscleGroups: ["Ombros", "Tríceps"], equipment: "Halteres", locations: ["Em casa", "Academia"], movement: "vertical_push", level: "Intermediário", impact: "baixo", tags: ["peso-livre", "ombros"], avoidWhen: ["shoulder_acute", "hypertension", "postpartum"], instructions: "Pressione os halteres mantendo costelas alinhadas e punhos sobre os cotovelos.", commonErrors: "Arquear a lombar ou aproximar os halteres com impacto.", alternativeIds: ["landmine_press", "shoulder_press_machine"] },
  { id: "barbell_row", name: "Remada curvada com barra", muscleGroups: ["Costas", "Bíceps", "Posteriores"], equipment: "Barra e anilhas", locations: ["Academia"], movement: "horizontal_pull", level: "Avançado", impact: "baixo", tags: ["peso-livre", "composto", "costas"], avoidWhen: ["back_acute"], instructions: "Incline o tronco com coluna neutra e puxe a barra em direção ao abdômen.", commonErrors: "Balançar o tronco ou encolher os ombros.", alternativeIds: ["seated_row", "chest_supported_row"] },
  { id: "one_arm_cable_row", name: "Remada unilateral na polia", muscleGroups: ["Costas", "Bíceps"], equipment: "Polia", locations: ["Academia"], movement: "horizontal_pull", level: "Intermediário", impact: "baixo", tags: ["cabo", "unilateral", "costas"], avoidWhen: ["shoulder_acute"], instructions: "Puxe o cotovelo para trás sem girar o tronco e retorne com controle.", commonErrors: "Rodar o corpo ou elevar o ombro.", alternativeIds: ["seated_row", "band_row"] },
  { id: "assisted_pullup", name: "Barra fixa assistida", muscleGroups: ["Costas", "Bíceps"], equipment: "Máquina assistida", locations: ["Academia"], movement: "vertical_pull", level: "Intermediário", impact: "baixo", tags: ["maquina", "composto", "costas"], avoidWhen: ["shoulder_acute"], instructions: "Desça os ombros e puxe o peito em direção à barra sem balançar.", commonErrors: "Encolher os ombros ou usar impulso.", alternativeIds: ["lat_pulldown", "seated_row"] },
  { id: "face_pull", name: "Face pull na polia", muscleGroups: ["Ombros", "Costas"], equipment: "Polia e corda", locations: ["Academia"], movement: "horizontal_pull", level: "Iniciante", impact: "baixo", tags: ["cabo", "postura", "ombros"], avoidWhen: ["shoulder_acute"], instructions: "Puxe a corda em direção ao rosto separando as pontas e mantendo o peito alto.", commonErrors: "Usar carga excessiva ou projetar a cabeça.", alternativeIds: ["band_row", "seated_row"] },
  { id: "lateral_raise", name: "Elevação lateral com halteres", muscleGroups: ["Ombros"], equipment: "Halteres", locations: ["Em casa", "Academia"], movement: "arms", level: "Iniciante", impact: "baixo", tags: ["peso-livre", "isolador", "ombros"], avoidWhen: ["shoulder_acute"], instructions: "Eleve os braços até a altura confortável mantendo cotovelos suaves.", commonErrors: "Dar impulso ou elevar os ombros.", alternativeIds: ["face_pull"] },
  { id: "preacher_curl_machine", name: "Rosca Scott na máquina", muscleGroups: ["Bíceps"], equipment: "Máquina Scott", locations: ["Academia"], movement: "arms", level: "Iniciante", impact: "baixo", tags: ["maquina", "isolador", "bracos"], avoidWhen: ["elbow_acute"], instructions: "Mantenha os braços apoiados e flexione sem retirar os ombros do encosto.", commonErrors: "Estender com impacto ou tirar os cotovelos do apoio.", alternativeIds: ["biceps_curl"] },
  { id: "cable_curl", name: "Rosca direta na polia", muscleGroups: ["Bíceps"], equipment: "Polia baixa", locations: ["Academia"], movement: "arms", level: "Iniciante", impact: "baixo", tags: ["cabo", "isolador", "bracos"], avoidWhen: ["elbow_acute"], instructions: "Mantenha os cotovelos junto ao corpo e flexione sem balançar.", commonErrors: "Avançar os cotovelos ou inclinar o tronco.", alternativeIds: ["biceps_curl"] },
  { id: "leg_extension", name: "Cadeira extensora", muscleGroups: ["Quadríceps"], equipment: "Cadeira extensora", locations: ["Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["maquina", "isolador", "pernas"], avoidWhen: ["knee_acute"], instructions: "Ajuste o eixo ao joelho e estenda com controle sem chutar a carga.", commonErrors: "Usar impulso ou tirar o quadril do banco.", alternativeIds: ["leg_press", "box_squat"] },
  { id: "leg_curl_seated", name: "Cadeira flexora", muscleGroups: ["Posteriores"], equipment: "Cadeira flexora", locations: ["Academia"], movement: "hinge", level: "Iniciante", impact: "baixo", tags: ["maquina", "isolador", "posterior"], avoidWhen: ["knee_acute"], instructions: "Flexione os joelhos mantendo quadril e tronco apoiados.", commonErrors: "Usar impulso ou deixar o quadril levantar.", alternativeIds: ["leg_curl", "romanian_deadlift_db"] },
  { id: "adductor_machine", name: "Cadeira adutora", muscleGroups: ["Adutores", "Quadril"], equipment: "Cadeira adutora", locations: ["Academia"], movement: "glute", level: "Iniciante", impact: "baixo", tags: ["maquina", "isolador", "quadril"], avoidWhen: ["hip_acute"], instructions: "Aproxime as pernas com controle mantendo costas apoiadas.", commonErrors: "Bater as placas ou fechar além do conforto.", alternativeIds: ["glute_bridge"] },
  { id: "abductor_machine", name: "Cadeira abdutora", muscleGroups: ["Glúteos", "Quadril"], equipment: "Cadeira abdutora", locations: ["Academia"], movement: "glute", level: "Iniciante", impact: "baixo", tags: ["maquina", "isolador", "gluteos"], avoidWhen: ["hip_acute"], instructions: "Afaste os joelhos sem perder o apoio do tronco e retorne devagar.", commonErrors: "Usar impulso ou girar os pés excessivamente.", alternativeIds: ["cable_kickback", "glute_bridge"] },
  { id: "pallof_press", name: "Pallof press", muscleGroups: ["Core"], equipment: "Polia ou elástico", locations: ["Em casa", "Academia"], movement: "core", level: "Intermediário", impact: "baixo", tags: ["cabo", "anti-rotacao", "core"], avoidWhen: ["abdominal_symptoms"], instructions: "Empurre as mãos à frente resistindo à rotação do tronco.", commonErrors: "Girar o quadril ou prender a respiração.", alternativeIds: ["bird_dog", "plank_incline"] },
  { id: "cable_crunch", name: "Abdominal na polia", muscleGroups: ["Core"], equipment: "Polia alta e corda", locations: ["Academia"], movement: "core", level: "Intermediário", impact: "baixo", tags: ["cabo", "core"], avoidWhen: ["back_acute", "postpartum", "abdominal_symptoms"], instructions: "Aproxime costelas e pelve sem puxar a corda apenas com os braços.", commonErrors: "Dobrar somente o quadril ou usar carga excessiva.", alternativeIds: ["dead_bug", "pallof_press"] },
  { id: "thoracic_rotation", name: "Rotação torácica", muscleGroups: ["Coluna torácica", "Ombros"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "mobility", level: "Iniciante", impact: "baixo", tags: ["mobilidade", "aquecimento"], avoidWhen: ["shoulder_acute"], instructions: "Gire o braço e o tronco acompanhando o movimento com a respiração.", commonErrors: "Forçar a lombar ou acelerar o movimento.", alternativeIds: ["cat_cow"] },
  { id: "dynamic_lunge_reach", name: "Afundo dinâmico com alcance", muscleGroups: ["Quadril", "Pernas", "Coluna torácica"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "mobility", level: "Intermediário", impact: "baixo", tags: ["mobilidade", "aquecimento", "corpo-inteiro"], avoidWhen: ["knee_acute", "balance_issue"], instructions: "Dê um passo confortável, apoie-se se necessário e alcance o braço sem perder o alinhamento.", commonErrors: "Passo curto demais ou rotação forçada.", alternativeIds: ["thoracic_rotation", "march"] },
  { id: "hamstring_stretch", name: "Alongamento de posteriores", muscleGroups: ["Posteriores"], equipment: "Banco ou colchonete", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["alongamento", "mobilidade"], avoidWhen: ["back_acute"], instructions: "Estenda a perna e incline o tronco a partir do quadril até sentir tensão leve.", commonErrors: "Arredondar a coluna ou forçar o joelho.", alternativeIds: ["breathing_reset"] },
  { id: "lat_stretch", name: "Alongamento de dorsais", muscleGroups: ["Costas", "Ombros"], equipment: "Banco ou apoio", locations: ["Em casa", "Academia"], movement: "cooldown", level: "Iniciante", impact: "baixo", tags: ["alongamento", "mobilidade"], avoidWhen: ["shoulder_acute"], instructions: "Apoie as mãos e leve o quadril para trás mantendo a respiração tranquila.", commonErrors: "Forçar os ombros ou prender a respiração.", alternativeIds: ["breathing_reset"] },
  { id: "breathing_360", name: "Respiração 360°", muscleGroups: ["Core", "Assoalho pélvico", "Respiratório"], equipment: "Nenhum", locations: ["Em casa", "Academia"], movement: "warmup", level: "Iniciante", impact: "baixo", tags: ["respiracao", "pos-parto", "core"], avoidWhen: [], instructions: "Inspire expandindo costelas e abdômen; expire suavemente sem sugar ou empurrar o abdômen.", commonErrors: "Prender o ar, forçar a contração ou elevar os ombros.", alternativeIds: ["breathing_reset", "pelvic_tilt"] },
  { id: "step_up", name: "Step-up com apoio", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Degrau e apoio estável", locations: ["Em casa", "Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["unilateral", "pernas", "pos-parto"], avoidWhen: ["knee_acute", "balance_issue"], instructions: "Suba em um degrau baixo com controle, use apoio e desça lentamente.", commonErrors: "Impulsionar com a perna de baixo ou perder o alinhamento do joelho.", alternativeIds: ["box_squat", "leg_press"] },
  { id: "assisted_lunge", name: "Afundo curto assistido", muscleGroups: ["Quadríceps", "Glúteos"], equipment: "Apoio estável", locations: ["Em casa", "Academia"], movement: "squat", level: "Iniciante", impact: "baixo", tags: ["unilateral", "pernas", "pos-parto"], avoidWhen: ["knee_acute", "balance_issue"], instructions: "Use apoio, faça um passo curto e desça apenas na amplitude sem dor ou pressão pélvica.", commonErrors: "Perder o equilíbrio, girar o joelho ou ampliar demais o passo.", alternativeIds: ["step_up", "box_squat"] },
  { id: "half_kneeling_landmine", name: "Landmine press meio-ajoelhado", muscleGroups: ["Ombros", "Tríceps", "Core"], equipment: "Landmine e colchonete", locations: ["Academia"], movement: "vertical_push", level: "Intermediário", impact: "baixo", tags: ["unilateral", "core", "pos-parto"], avoidWhen: ["shoulder_acute", "knee_acute"], instructions: "Mantenha costelas sobre a pelve e empurre a barra em diagonal enquanto expira.", commonErrors: "Arquear a lombar, prender o ar ou perder o alinhamento da pelve.", alternativeIds: ["landmine_press", "wall_pushup"] },
  { id: "suitcase_carry", name: "Suitcase carry", muscleGroups: ["Core", "Antebraços", "Quadril"], equipment: "Halter ou kettlebell", locations: ["Em casa", "Academia"], movement: "core", level: "Intermediário", impact: "baixo", tags: ["carry", "unilateral", "pos-parto"], avoidWhen: ["back_acute", "balance_issue", "abdominal_symptoms"], instructions: "Caminhe ereta com a carga em uma mão, sem inclinar o tronco e respirando normalmente.", commonErrors: "Inclinar para o lado, prender o ar ou iniciar com carga alta.", alternativeIds: ["pallof_press", "bird_dog"] },
  { id: "farmer_carry", name: "Farmer carry", muscleGroups: ["Core", "Antebraços", "Corpo inteiro"], equipment: "Halteres ou kettlebells", locations: ["Em casa", "Academia"], movement: "core", level: "Intermediário", impact: "baixo", tags: ["carry", "composto", "pos-parto"], avoidWhen: ["back_acute", "balance_issue", "abdominal_symptoms"], instructions: "Caminhe com passos curtos, postura alta e respiração contínua.", commonErrors: "Usar carga que altera a postura ou prender a respiração.", alternativeIds: ["suitcase_carry", "pallof_press"] },
  { id: "side_plank_knees", name: "Prancha lateral com joelhos", muscleGroups: ["Core", "Glúteos"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Iniciante", impact: "baixo", tags: ["core", "isometria", "pos-parto"], avoidWhen: ["shoulder_acute", "abdominal_symptoms"], instructions: "Apoie antebraço e joelhos, eleve o quadril e respire sem abaulamento abdominal.", commonErrors: "Prender o ar, perder o alinhamento ou insistir com pressão pélvica.", alternativeIds: ["bird_dog", "pallof_press"] },
  { id: "bear_hover_short", name: "Bear hover curto", muscleGroups: ["Core", "Ombros", "Quadríceps"], equipment: "Colchonete", locations: ["Em casa", "Academia"], movement: "core", level: "Intermediário", impact: "baixo", tags: ["core", "isometria", "pos-parto"], avoidWhen: ["wrist_acute", "shoulder_acute", "abdominal_symptoms"], instructions: "Eleve os joelhos poucos centímetros por poucos segundos, expirando e sem abaulamento abdominal.", commonErrors: "Sustentar por tempo excessivo, prender o ar ou perder o controle da parede abdominal.", alternativeIds: ["dead_bug", "bird_dog"] },
];

export const exerciseById = new Map(exercises.map((exercise) => [exercise.id, exercise]));
